/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateGroupTypePayload
 */
public class CreateGroupTypePayloadTest {
    private final CreateGroupTypePayload model = new CreateGroupTypePayload();

    /**
     * Model tests for CreateGroupTypePayload
     */
    @Test
    public void testCreateGroupTypePayload() {
        // TODO: test CreateGroupTypePayload
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'xGroupsAsTeams'
     */
    @Test
    public void xGroupsAsTeamsTest() {
        // TODO: test xGroupsAsTeams
    }

}
