/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateLikePayload
 */
public class CreateLikePayloadTest {
    private final CreateLikePayload model = new CreateLikePayload();

    /**
     * Model tests for CreateLikePayload
     */
    @Test
    public void testCreateLikePayload() {
        // TODO: test CreateLikePayload
    }

    /**
     * Test the property 'likedByCurrentProfile'
     */
    @Test
    public void likedByCurrentProfileTest() {
        // TODO: test likedByCurrentProfile
    }

    /**
     * Test the property 'likesCount'
     */
    @Test
    public void likesCountTest() {
        // TODO: test likesCount
    }

}
