/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FieldLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Field
 */
public class FieldTest {
    private final Field model = new Field();

    /**
     * Model tests for Field
     */
    @Test
    public void testField() {
        // TODO: test Field
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'deletable'
     */
    @Test
    public void deletableTest() {
        // TODO: test deletable
    }

    /**
     * Test the property 'validFormatInfo'
     */
    @Test
    public void validFormatInfoTest() {
        // TODO: test validFormatInfo
    }

    /**
     * Test the property 'blockIndex'
     */
    @Test
    public void blockIndexTest() {
        // TODO: test blockIndex
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'example'
     */
    @Test
    public void exampleTest() {
        // TODO: test example
    }

    /**
     * Test the property 'xKonfigOriginalExample'
     */
    @Test
    public void xKonfigOriginalExampleTest() {
        // TODO: test xKonfigOriginalExample
    }

}
