/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GenericNotification;
import com.konfigthis.client.model.GetNotificationsResponseLinked;
import com.konfigthis.client.model.GetNotificationsResponseLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetNotificationsResponse
 */
public class GetNotificationsResponseTest {
    private final GetNotificationsResponse model = new GetNotificationsResponse();

    /**
     * Model tests for GetNotificationsResponse
     */
    @Test
    public void testGetNotificationsResponse() {
        // TODO: test GetNotificationsResponse
    }

    /**
     * Test the property 'notifications'
     */
    @Test
    public void notificationsTest() {
        // TODO: test notifications
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'linked'
     */
    @Test
    public void linkedTest() {
        // TODO: test linked
    }

}
