/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GroupType
 */
public class GroupTypeTest {
    private final GroupType model = new GroupType();

    /**
     * Model tests for GroupType
     */
    @Test
    public void testGroupType() {
        // TODO: test GroupType
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fieldName'
     */
    @Test
    public void fieldNameTest() {
        // TODO: test fieldName
    }

    /**
     * Test the property 'deletable'
     */
    @Test
    public void deletableTest() {
        // TODO: test deletable
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'xGroupsAsTeams'
     */
    @Test
    public void xGroupsAsTeamsTest() {
        // TODO: test xGroupsAsTeams
    }

}
