/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GroupsTeamsGetAllGroupTypesResponseLinks
 */
public class GroupsTeamsGetAllGroupTypesResponseLinksTest {
    private final GroupsTeamsGetAllGroupTypesResponseLinks model = new GroupsTeamsGetAllGroupTypesResponseLinks();

    /**
     * Model tests for GroupsTeamsGetAllGroupTypesResponseLinks
     */
    @Test
    public void testGroupsTeamsGetAllGroupTypesResponseLinks() {
        // TODO: test GroupsTeamsGetAllGroupTypesResponseLinks
    }

    /**
     * Test the property 'groupTypeGroup'
     */
    @Test
    public void groupTypeGroupTest() {
        // TODO: test groupTypeGroup
    }

}
