/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HomeFeedRemoveEventCommentResponse
 */
public class HomeFeedRemoveEventCommentResponseTest {
    private final HomeFeedRemoveEventCommentResponse model = new HomeFeedRemoveEventCommentResponse();

    /**
     * Model tests for HomeFeedRemoveEventCommentResponse
     */
    @Test
    public void testHomeFeedRemoveEventCommentResponse() {
        // TODO: test HomeFeedRemoveEventCommentResponse
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
