/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JobTier;
import com.konfigthis.client.model.JobsInfoCreateJobTierResponseLinked;
import com.konfigthis.client.model.JobsInfoGetAllJobTiersResponseLinks;
import com.konfigthis.client.model.Meta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobsInfoUpdateLabelResponse
 */
public class JobsInfoUpdateLabelResponseTest {
    private final JobsInfoUpdateLabelResponse model = new JobsInfoUpdateLabelResponse();

    /**
     * Model tests for JobsInfoUpdateLabelResponse
     */
    @Test
    public void testJobsInfoUpdateLabelResponse() {
        // TODO: test JobsInfoUpdateLabelResponse
    }

    /**
     * Test the property 'jobTiers'
     */
    @Test
    public void jobTiersTest() {
        // TODO: test jobTiers
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'linked'
     */
    @Test
    public void linkedTest() {
        // TODO: test linked
    }

}
