/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Field;
import com.konfigthis.client.model.ProfileFieldsGetAllFieldsResponseLinked;
import com.konfigthis.client.model.ProfileFieldsGetAllFieldsResponseLinks;
import com.konfigthis.client.model.ProfileFieldsUpdateFieldInSectionResponseMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProfileFieldsUpdateFieldInSectionResponse
 */
public class ProfileFieldsUpdateFieldInSectionResponseTest {
    private final ProfileFieldsUpdateFieldInSectionResponse model = new ProfileFieldsUpdateFieldInSectionResponse();

    /**
     * Model tests for ProfileFieldsUpdateFieldInSectionResponse
     */
    @Test
    public void testProfileFieldsUpdateFieldInSectionResponse() {
        // TODO: test ProfileFieldsUpdateFieldInSectionResponse
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'linked'
     */
    @Test
    public void linkedTest() {
        // TODO: test linked
    }

}
