/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Resource
 */
public class ResourceTest {
    private final Resource model = new Resource();

    /**
     * Model tests for Resource
     */
    @Test
    public void testResource() {
        // TODO: test Resource
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'fileFormat'
     */
    @Test
    public void fileFormatTest() {
        // TODO: test fileFormat
    }

    /**
     * Test the property 'fileSize'
     */
    @Test
    public void fileSizeTest() {
        // TODO: test fileSize
    }

    /**
     * Test the property 'fileUrl'
     */
    @Test
    public void fileUrlTest() {
        // TODO: test fileUrl
    }

    /**
     * Test the property 'lastEdited'
     */
    @Test
    public void lastEditedTest() {
        // TODO: test lastEdited
    }

    /**
     * Test the property 'folderId'
     */
    @Test
    public void folderIdTest() {
        // TODO: test folderId
    }

}
