/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Salary
 */
public class SalaryTest {
    private final Salary model = new Salary();

    /**
     * Model tests for Salary
     */
    @Test
    public void testSalary() {
        // TODO: test Salary
    }

    /**
     * Test the property 'currencyType'
     */
    @Test
    public void currencyTypeTest() {
        // TODO: test currencyType
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'payGroupId'
     */
    @Test
    public void payGroupIdTest() {
        // TODO: test payGroupId
    }

    /**
     * Test the property 'payrollJobId'
     */
    @Test
    public void payrollJobIdTest() {
        // TODO: test payrollJobId
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'yearlyAmount'
     */
    @Test
    public void yearlyAmountTest() {
        // TODO: test yearlyAmount
    }

    /**
     * Test the property 'hourly'
     */
    @Test
    public void hourlyTest() {
        // TODO: test hourly
    }

    /**
     * Test the property 'amountRaw'
     */
    @Test
    public void amountRawTest() {
        // TODO: test amountRaw
    }

    /**
     * Test the property 'payrollCompany'
     */
    @Test
    public void payrollCompanyTest() {
        // TODO: test payrollCompany
    }

    /**
     * Test the property 'payrollJob'
     */
    @Test
    public void payrollJobTest() {
        // TODO: test payrollJob
    }

}
