/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CreateEventPayload
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CreateEventPayload {
  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private String content;

  public static final String SERIALIZED_NAME_IS_APPRECIATION = "is_appreciation";
  @SerializedName(SERIALIZED_NAME_IS_APPRECIATION)
  private Boolean isAppreciation = false;

  public static final String SERIALIZED_NAME_FILE_ID = "file_id";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_EMAIL_ALL = "email_all";
  @SerializedName(SERIALIZED_NAME_EMAIL_ALL)
  private Boolean emailAll = false;

  public CreateEventPayload() {
  }

  public CreateEventPayload content(String content) {
    
    
    
    
    this.content = content;
    return this;
  }

   /**
   * the content of the announcement; formatted in markdown; to @mention a profile, use format: &lt;code&gt;[full_name](https://developers.namely.com/)&lt;/code&gt; where {profile_id} is the &lt;code&gt;id&lt;/code&gt; of the profile you want to mention
   * @return content
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "the content of the announcement; formatted in markdown; to @mention a profile, use format: <code>[full_name](https://developers.namely.com/)</code> where {profile_id} is the <code>id</code> of the profile you want to mention")

  public String getContent() {
    return content;
  }


  public void setContent(String content) {
    
    
    
    this.content = content;
  }


  public CreateEventPayload isAppreciation(Boolean isAppreciation) {
    
    
    
    
    this.isAppreciation = isAppreciation;
    return this;
  }

   /**
   * if &lt;code&gt;true&lt;/code&gt;, any @mentioned profile will be appreciated
   * @return isAppreciation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "if <code>true</code>, any @mentioned profile will be appreciated")

  public Boolean getIsAppreciation() {
    return isAppreciation;
  }


  public void setIsAppreciation(Boolean isAppreciation) {
    
    
    
    this.isAppreciation = isAppreciation;
  }


  public CreateEventPayload fileId(String fileId) {
    
    
    
    
    this.fileId = fileId;
    return this;
  }

   /**
   * Get fileId
   * @return fileId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFileId() {
    return fileId;
  }


  public void setFileId(String fileId) {
    
    
    
    this.fileId = fileId;
  }


  public CreateEventPayload emailAll(Boolean emailAll) {
    
    
    
    
    this.emailAll = emailAll;
    return this;
  }

   /**
   * if &lt;code&gt;true&lt;/code&gt;, will send an email to all active profiles per their company email address; will only be successful is token bearer has the corresponding permissions
   * @return emailAll
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "if <code>true</code>, will send an email to all active profiles per their company email address; will only be successful is token bearer has the corresponding permissions")

  public Boolean getEmailAll() {
    return emailAll;
  }


  public void setEmailAll(Boolean emailAll) {
    
    
    
    this.emailAll = emailAll;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateEventPayload instance itself
   */
  public CreateEventPayload putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateEventPayload createEventPayload = (CreateEventPayload) o;
    return Objects.equals(this.content, createEventPayload.content) &&
        Objects.equals(this.isAppreciation, createEventPayload.isAppreciation) &&
        Objects.equals(this.fileId, createEventPayload.fileId) &&
        Objects.equals(this.emailAll, createEventPayload.emailAll)&&
        Objects.equals(this.additionalProperties, createEventPayload.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, isAppreciation, fileId, emailAll, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateEventPayload {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    isAppreciation: ").append(toIndentedString(isAppreciation)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    emailAll: ").append(toIndentedString(emailAll)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("content");
    openapiFields.add("is_appreciation");
    openapiFields.add("file_id");
    openapiFields.add("email_all");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("content");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateEventPayload
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateEventPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateEventPayload is not found in the empty JSON string", CreateEventPayload.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateEventPayload.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("content").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content").toString()));
      }
      if ((jsonObj.get("file_id") != null && !jsonObj.get("file_id").isJsonNull()) && !jsonObj.get("file_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `file_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("file_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateEventPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateEventPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateEventPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateEventPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateEventPayload>() {
           @Override
           public void write(JsonWriter out, CreateEventPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateEventPayload read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CreateEventPayload instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateEventPayload given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateEventPayload
  * @throws IOException if the JSON string is invalid with respect to CreateEventPayload
  */
  public static CreateEventPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateEventPayload.class);
  }

 /**
  * Convert an instance of CreateEventPayload to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

