/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GetGroupsResponseLinked;
import com.konfigthis.client.model.GetGroupsResponseLinks;
import com.konfigthis.client.model.GroupSingular;
import com.konfigthis.client.model.MetaGroup;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GroupsTeamsGetGroupDetailsResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GroupsTeamsGetGroupDetailsResponse {
  public static final String SERIALIZED_NAME_GROUPS = "groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  private List<GroupSingular> groups = null;

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  private MetaGroup meta;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private GetGroupsResponseLinks links;

  public static final String SERIALIZED_NAME_LINKED = "linked";
  @SerializedName(SERIALIZED_NAME_LINKED)
  private GetGroupsResponseLinked linked;

  public GroupsTeamsGetGroupDetailsResponse() {
  }

  public GroupsTeamsGetGroupDetailsResponse groups(List<GroupSingular> groups) {
    
    
    
    
    this.groups = groups;
    return this;
  }

  public GroupsTeamsGetGroupDetailsResponse addGroupsItem(GroupSingular groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<GroupSingular> getGroups() {
    return groups;
  }


  public void setGroups(List<GroupSingular> groups) {
    
    
    
    this.groups = groups;
  }


  public GroupsTeamsGetGroupDetailsResponse meta(MetaGroup meta) {
    
    
    
    
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MetaGroup getMeta() {
    return meta;
  }


  public void setMeta(MetaGroup meta) {
    
    
    
    this.meta = meta;
  }


  public GroupsTeamsGetGroupDetailsResponse links(GetGroupsResponseLinks links) {
    
    
    
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetGroupsResponseLinks getLinks() {
    return links;
  }


  public void setLinks(GetGroupsResponseLinks links) {
    
    
    
    this.links = links;
  }


  public GroupsTeamsGetGroupDetailsResponse linked(GetGroupsResponseLinked linked) {
    
    
    
    
    this.linked = linked;
    return this;
  }

   /**
   * Get linked
   * @return linked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetGroupsResponseLinked getLinked() {
    return linked;
  }


  public void setLinked(GetGroupsResponseLinked linked) {
    
    
    
    this.linked = linked;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GroupsTeamsGetGroupDetailsResponse instance itself
   */
  public GroupsTeamsGetGroupDetailsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupsTeamsGetGroupDetailsResponse groupsTeamsGetGroupDetailsResponse = (GroupsTeamsGetGroupDetailsResponse) o;
    return Objects.equals(this.groups, groupsTeamsGetGroupDetailsResponse.groups) &&
        Objects.equals(this.meta, groupsTeamsGetGroupDetailsResponse.meta) &&
        Objects.equals(this.links, groupsTeamsGetGroupDetailsResponse.links) &&
        Objects.equals(this.linked, groupsTeamsGetGroupDetailsResponse.linked)&&
        Objects.equals(this.additionalProperties, groupsTeamsGetGroupDetailsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups, meta, links, linked, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupsTeamsGetGroupDetailsResponse {\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    linked: ").append(toIndentedString(linked)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("groups");
    openapiFields.add("meta");
    openapiFields.add("links");
    openapiFields.add("linked");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GroupsTeamsGetGroupDetailsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GroupsTeamsGetGroupDetailsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupsTeamsGetGroupDetailsResponse is not found in the empty JSON string", GroupsTeamsGetGroupDetailsResponse.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("groups") != null && !jsonObj.get("groups").isJsonNull()) {
        JsonArray jsonArraygroups = jsonObj.getAsJsonArray("groups");
        if (jsonArraygroups != null) {
          // ensure the json data is an array
          if (!jsonObj.get("groups").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `groups` to be an array in the JSON string but got `%s`", jsonObj.get("groups").toString()));
          }

          // validate the optional field `groups` (array)
          for (int i = 0; i < jsonArraygroups.size(); i++) {
            GroupSingular.validateJsonObject(jsonArraygroups.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `meta`
      if (jsonObj.get("meta") != null && !jsonObj.get("meta").isJsonNull()) {
        MetaGroup.validateJsonObject(jsonObj.getAsJsonObject("meta"));
      }
      // validate the optional field `links`
      if (jsonObj.get("links") != null && !jsonObj.get("links").isJsonNull()) {
        GetGroupsResponseLinks.validateJsonObject(jsonObj.getAsJsonObject("links"));
      }
      // validate the optional field `linked`
      if (jsonObj.get("linked") != null && !jsonObj.get("linked").isJsonNull()) {
        GetGroupsResponseLinked.validateJsonObject(jsonObj.getAsJsonObject("linked"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupsTeamsGetGroupDetailsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupsTeamsGetGroupDetailsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupsTeamsGetGroupDetailsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupsTeamsGetGroupDetailsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupsTeamsGetGroupDetailsResponse>() {
           @Override
           public void write(JsonWriter out, GroupsTeamsGetGroupDetailsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupsTeamsGetGroupDetailsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GroupsTeamsGetGroupDetailsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GroupsTeamsGetGroupDetailsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GroupsTeamsGetGroupDetailsResponse
  * @throws IOException if the JSON string is invalid with respect to GroupsTeamsGetGroupDetailsResponse
  */
  public static GroupsTeamsGetGroupDetailsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupsTeamsGetGroupDetailsResponse.class);
  }

 /**
  * Convert an instance of GroupsTeamsGetGroupDetailsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

