/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Meta;
import com.konfigthis.client.model.ProfileFieldsGetAllFieldSectionsResponseLinked;
import com.konfigthis.client.model.ProfileFieldsGetAllFieldSectionsResponseLinks;
import com.konfigthis.client.model.Section;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ProfileFieldsGetAllFieldSectionsResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProfileFieldsGetAllFieldSectionsResponse {
  public static final String SERIALIZED_NAME_SECTIONS = "sections";
  @SerializedName(SERIALIZED_NAME_SECTIONS)
  private List<Section> sections = null;

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  private Meta meta;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private ProfileFieldsGetAllFieldSectionsResponseLinks links;

  public static final String SERIALIZED_NAME_LINKED = "linked";
  @SerializedName(SERIALIZED_NAME_LINKED)
  private ProfileFieldsGetAllFieldSectionsResponseLinked linked;

  public ProfileFieldsGetAllFieldSectionsResponse() {
  }

  public ProfileFieldsGetAllFieldSectionsResponse sections(List<Section> sections) {
    
    
    
    
    this.sections = sections;
    return this;
  }

  public ProfileFieldsGetAllFieldSectionsResponse addSectionsItem(Section sectionsItem) {
    if (this.sections == null) {
      this.sections = new ArrayList<>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

   /**
   * Get sections
   * @return sections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Section> getSections() {
    return sections;
  }


  public void setSections(List<Section> sections) {
    
    
    
    this.sections = sections;
  }


  public ProfileFieldsGetAllFieldSectionsResponse meta(Meta meta) {
    
    
    
    
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Meta getMeta() {
    return meta;
  }


  public void setMeta(Meta meta) {
    
    
    
    this.meta = meta;
  }


  public ProfileFieldsGetAllFieldSectionsResponse links(ProfileFieldsGetAllFieldSectionsResponseLinks links) {
    
    
    
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProfileFieldsGetAllFieldSectionsResponseLinks getLinks() {
    return links;
  }


  public void setLinks(ProfileFieldsGetAllFieldSectionsResponseLinks links) {
    
    
    
    this.links = links;
  }


  public ProfileFieldsGetAllFieldSectionsResponse linked(ProfileFieldsGetAllFieldSectionsResponseLinked linked) {
    
    
    
    
    this.linked = linked;
    return this;
  }

   /**
   * Get linked
   * @return linked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProfileFieldsGetAllFieldSectionsResponseLinked getLinked() {
    return linked;
  }


  public void setLinked(ProfileFieldsGetAllFieldSectionsResponseLinked linked) {
    
    
    
    this.linked = linked;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProfileFieldsGetAllFieldSectionsResponse instance itself
   */
  public ProfileFieldsGetAllFieldSectionsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileFieldsGetAllFieldSectionsResponse profileFieldsGetAllFieldSectionsResponse = (ProfileFieldsGetAllFieldSectionsResponse) o;
    return Objects.equals(this.sections, profileFieldsGetAllFieldSectionsResponse.sections) &&
        Objects.equals(this.meta, profileFieldsGetAllFieldSectionsResponse.meta) &&
        Objects.equals(this.links, profileFieldsGetAllFieldSectionsResponse.links) &&
        Objects.equals(this.linked, profileFieldsGetAllFieldSectionsResponse.linked)&&
        Objects.equals(this.additionalProperties, profileFieldsGetAllFieldSectionsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sections, meta, links, linked, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileFieldsGetAllFieldSectionsResponse {\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    linked: ").append(toIndentedString(linked)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sections");
    openapiFields.add("meta");
    openapiFields.add("links");
    openapiFields.add("linked");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProfileFieldsGetAllFieldSectionsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProfileFieldsGetAllFieldSectionsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProfileFieldsGetAllFieldSectionsResponse is not found in the empty JSON string", ProfileFieldsGetAllFieldSectionsResponse.openapiRequiredFields.toString()));
        }
      }
      if (jsonObj.get("sections") != null && !jsonObj.get("sections").isJsonNull()) {
        JsonArray jsonArraysections = jsonObj.getAsJsonArray("sections");
        if (jsonArraysections != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sections").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sections` to be an array in the JSON string but got `%s`", jsonObj.get("sections").toString()));
          }

          // validate the optional field `sections` (array)
          for (int i = 0; i < jsonArraysections.size(); i++) {
            Section.validateJsonObject(jsonArraysections.get(i).getAsJsonObject());
          };
        }
      }
      // validate the optional field `meta`
      if (jsonObj.get("meta") != null && !jsonObj.get("meta").isJsonNull()) {
        Meta.validateJsonObject(jsonObj.getAsJsonObject("meta"));
      }
      // validate the optional field `links`
      if (jsonObj.get("links") != null && !jsonObj.get("links").isJsonNull()) {
        ProfileFieldsGetAllFieldSectionsResponseLinks.validateJsonObject(jsonObj.getAsJsonObject("links"));
      }
      // validate the optional field `linked`
      if (jsonObj.get("linked") != null && !jsonObj.get("linked").isJsonNull()) {
        ProfileFieldsGetAllFieldSectionsResponseLinked.validateJsonObject(jsonObj.getAsJsonObject("linked"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProfileFieldsGetAllFieldSectionsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProfileFieldsGetAllFieldSectionsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProfileFieldsGetAllFieldSectionsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProfileFieldsGetAllFieldSectionsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProfileFieldsGetAllFieldSectionsResponse>() {
           @Override
           public void write(JsonWriter out, ProfileFieldsGetAllFieldSectionsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProfileFieldsGetAllFieldSectionsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProfileFieldsGetAllFieldSectionsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProfileFieldsGetAllFieldSectionsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProfileFieldsGetAllFieldSectionsResponse
  * @throws IOException if the JSON string is invalid with respect to ProfileFieldsGetAllFieldSectionsResponse
  */
  public static ProfileFieldsGetAllFieldSectionsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProfileFieldsGetAllFieldSectionsResponse.class);
  }

 /**
  * Convert an instance of ProfileFieldsGetAllFieldSectionsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

