/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.GetNotificationsResponse;
import com.konfigthis.client.model.NotificationsGetProfileNotificationsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificationsApi
 */
@Disabled
public class NotificationsApiTest {

    private static NotificationsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new NotificationsApi(apiClient);
    }

    /**
     * Get a Profile&#39;s Notifications
     *
     * Returns notifications for a profile in a paginated form. By default, there will be 30 notifications per page. At most, you can request 50 notifications per page.  There are three main types of notifications: 1. Time Off 2. Mentioned/Appreciated 3. Generic (All Other)  &lt;strong&gt;There are also three \&quot;200\&quot; responses on this page&lt;/strong&gt;. However, the actual notification response is a combination of all three responses (assuming the user has received all three types of notifications).  Time Off and Mentioned/Appreciated have distinct \&quot;links\&quot; associated with the notification object. Certain keys will be present or absent based on the nature of notification (e.g. the \&quot;comment_id\&quot; key will only be present if you were mentioned in a comment).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProfileNotificationsTest() throws ApiException {
        String id = null;
        Integer page = null;
        Integer perPage = null;
        NotificationsGetProfileNotificationsResponse response = api.getProfileNotifications(id)
                .page(page)
                .perPage(perPage)
                .execute();
        // TODO: test validations
    }

    /**
     * Get all Notifications
     *
     * Returns all notifications for the current API user/token bearer.  There are three main types of notifications: 1. Time Off 2. Mentioned/Appreciated 3. Generic (All Other)  &lt;strong&gt;There are also three \&quot;200\&quot; responses on this page&lt;/strong&gt;. However, the actual notification response is a combination of all three responses (assuming the user has received all three types of notifications).  Time Off and Mentioned/Appreciated have distinct \&quot;links\&quot; associated with the notification object. Certain keys will be present or absent based on the nature of notification (e.g. the \&quot;comment_id\&quot; key will only be present if you were mentioned in a comment).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void notificationsTest() throws ApiException {
        GetNotificationsResponse response = api.notifications()
                .execute();
        // TODO: test validations
    }

}
