/*
 * Namely API
 * Move your app forward with the Namely API Move your app forward with the Namely API
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.CreateJobTier;
import com.konfigthis.client.model.CreateJobTierPayload;
import com.konfigthis.client.model.JobsInfoCreateJobTierResponse;
import com.konfigthis.client.model.JobsInfoGetAllJobTiersResponse;
import com.konfigthis.client.model.JobsInfoGetJobTierResponse;
import com.konfigthis.client.model.JobsInfoUpdateLabelResponse;
import com.konfigthis.client.model.UpdateJobTier;
import com.konfigthis.client.model.UpdateJobTierPayload;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class JobTierApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public JobTierApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public JobTierApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createJobTierCall(CreateJobTier createJobTier, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createJobTier;

        // create path and map variables
        String localVarPath = "/job_tiers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createJobTierValidateBeforeCall(CreateJobTier createJobTier, final ApiCallback _callback) throws ApiException {
        return createJobTierCall(createJobTier, _callback);

    }


    private ApiResponse<JobsInfoCreateJobTierResponse> createJobTierWithHttpInfo(CreateJobTier createJobTier) throws ApiException {
        okhttp3.Call localVarCall = createJobTierValidateBeforeCall(createJobTier, null);
        Type localVarReturnType = new TypeToken<JobsInfoCreateJobTierResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createJobTierAsync(CreateJobTier createJobTier, final ApiCallback<JobsInfoCreateJobTierResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = createJobTierValidateBeforeCall(createJobTier, _callback);
        Type localVarReturnType = new TypeToken<JobsInfoCreateJobTierResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreateJobTierRequestBuilder {
        private final List<CreateJobTierPayload> jobTiers;

        private CreateJobTierRequestBuilder(List<CreateJobTierPayload> jobTiers) {
            this.jobTiers = jobTiers;
        }

        /**
         * Build call for createJobTier
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateJobTier createJobTier = buildBodyParams();
            return createJobTierCall(createJobTier, _callback);
        }

        private CreateJobTier buildBodyParams() {
            CreateJobTier createJobTier = new CreateJobTier();
            createJobTier.jobTiers(this.jobTiers);
            return createJobTier;
        }

        /**
         * Execute createJobTier request
         * @return JobsInfoCreateJobTierResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create Response </td><td>  -  </td></tr>
         </table>
         */
        public JobsInfoCreateJobTierResponse execute() throws ApiException {
            CreateJobTier createJobTier = buildBodyParams();
            ApiResponse<JobsInfoCreateJobTierResponse> localVarResp = createJobTierWithHttpInfo(createJobTier);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute createJobTier request with HTTP info returned
         * @return ApiResponse&lt;JobsInfoCreateJobTierResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<JobsInfoCreateJobTierResponse> executeWithHttpInfo() throws ApiException {
            CreateJobTier createJobTier = buildBodyParams();
            return createJobTierWithHttpInfo(createJobTier);
        }

        /**
         * Execute createJobTier request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 201 </td><td> Create Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<JobsInfoCreateJobTierResponse> _callback) throws ApiException {
            CreateJobTier createJobTier = buildBodyParams();
            return createJobTierAsync(createJobTier, _callback);
        }
    }

    /**
     * Create a Job Tier
     * Creates a job tier.
     * @return CreateJobTierRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Create Response </td><td>  -  </td></tr>
     </table>
     */
    public CreateJobTierRequestBuilder createJobTier(List<CreateJobTierPayload> jobTiers) throws IllegalArgumentException {
        if (jobTiers == null) throw new IllegalArgumentException("\"jobTiers\" is required but got null");
        return new CreateJobTierRequestBuilder(jobTiers);
    }
    private okhttp3.Call getAllJobTiersCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/job_tiers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllJobTiersValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getAllJobTiersCall(_callback);

    }


    private ApiResponse<JobsInfoGetAllJobTiersResponse> getAllJobTiersWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getAllJobTiersValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<JobsInfoGetAllJobTiersResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getAllJobTiersAsync(final ApiCallback<JobsInfoGetAllJobTiersResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllJobTiersValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<JobsInfoGetAllJobTiersResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetAllJobTiersRequestBuilder {

        private GetAllJobTiersRequestBuilder() {
        }

        /**
         * Build call for getAllJobTiers
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getAllJobTiersCall(_callback);
        }


        /**
         * Execute getAllJobTiers request
         * @return JobsInfoGetAllJobTiersResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public JobsInfoGetAllJobTiersResponse execute() throws ApiException {
            ApiResponse<JobsInfoGetAllJobTiersResponse> localVarResp = getAllJobTiersWithHttpInfo();
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getAllJobTiers request with HTTP info returned
         * @return ApiResponse&lt;JobsInfoGetAllJobTiersResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<JobsInfoGetAllJobTiersResponse> executeWithHttpInfo() throws ApiException {
            return getAllJobTiersWithHttpInfo();
        }

        /**
         * Execute getAllJobTiers request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<JobsInfoGetAllJobTiersResponse> _callback) throws ApiException {
            return getAllJobTiersAsync(_callback);
        }
    }

    /**
     * Get all Job Tiers
     * Returns an array of all job tiers. Each job tier can have zero to many linked job titles (while each job title must have one and only one linked job tier).
     * @return GetAllJobTiersRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public GetAllJobTiersRequestBuilder getAllJobTiers() throws IllegalArgumentException {
        return new GetAllJobTiersRequestBuilder();
    }
    private okhttp3.Call getJobTierCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/job_tiers/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getJobTierValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getJobTier(Async)");
        }

        return getJobTierCall(id, _callback);

    }


    private ApiResponse<JobsInfoGetJobTierResponse> getJobTierWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getJobTierValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<JobsInfoGetJobTierResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getJobTierAsync(String id, final ApiCallback<JobsInfoGetJobTierResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getJobTierValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<JobsInfoGetJobTierResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetJobTierRequestBuilder {
        private final String id;

        private GetJobTierRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getJobTier
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getJobTierCall(id, _callback);
        }


        /**
         * Execute getJobTier request
         * @return JobsInfoGetJobTierResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public JobsInfoGetJobTierResponse execute() throws ApiException {
            ApiResponse<JobsInfoGetJobTierResponse> localVarResp = getJobTierWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getJobTier request with HTTP info returned
         * @return ApiResponse&lt;JobsInfoGetJobTierResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<JobsInfoGetJobTierResponse> executeWithHttpInfo() throws ApiException {
            return getJobTierWithHttpInfo(id);
        }

        /**
         * Execute getJobTier request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<JobsInfoGetJobTierResponse> _callback) throws ApiException {
            return getJobTierAsync(id, _callback);
        }
    }

    /**
     * Get a Job Tier
     * Returns information about a single job tier.
     * @param id &lt;code&gt;id&lt;/code&gt; of the job tier you want to view (required)
     * @return GetJobTierRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public GetJobTierRequestBuilder getJobTier(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetJobTierRequestBuilder(id);
    }
    private okhttp3.Call updateLabelCall(String id, UpdateJobTier updateJobTier, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateJobTier;

        // create path and map variables
        String localVarPath = "/job_tiers/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "Authorization" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateLabelValidateBeforeCall(String id, UpdateJobTier updateJobTier, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling updateLabel(Async)");
        }

        return updateLabelCall(id, updateJobTier, _callback);

    }


    private ApiResponse<JobsInfoUpdateLabelResponse> updateLabelWithHttpInfo(String id, UpdateJobTier updateJobTier) throws ApiException {
        okhttp3.Call localVarCall = updateLabelValidateBeforeCall(id, updateJobTier, null);
        Type localVarReturnType = new TypeToken<JobsInfoUpdateLabelResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call updateLabelAsync(String id, UpdateJobTier updateJobTier, final ApiCallback<JobsInfoUpdateLabelResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateLabelValidateBeforeCall(id, updateJobTier, _callback);
        Type localVarReturnType = new TypeToken<JobsInfoUpdateLabelResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class UpdateLabelRequestBuilder {
        private final List<UpdateJobTierPayload> jobTiers;
        private final String id;

        private UpdateLabelRequestBuilder(List<UpdateJobTierPayload> jobTiers, String id) {
            this.jobTiers = jobTiers;
            this.id = id;
        }

        /**
         * Build call for updateLabel
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            UpdateJobTier updateJobTier = buildBodyParams();
            return updateLabelCall(id, updateJobTier, _callback);
        }

        private UpdateJobTier buildBodyParams() {
            UpdateJobTier updateJobTier = new UpdateJobTier();
            updateJobTier.jobTiers(this.jobTiers);
            return updateJobTier;
        }

        /**
         * Execute updateLabel request
         * @return JobsInfoUpdateLabelResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public JobsInfoUpdateLabelResponse execute() throws ApiException {
            UpdateJobTier updateJobTier = buildBodyParams();
            ApiResponse<JobsInfoUpdateLabelResponse> localVarResp = updateLabelWithHttpInfo(id, updateJobTier);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute updateLabel request with HTTP info returned
         * @return ApiResponse&lt;JobsInfoUpdateLabelResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<JobsInfoUpdateLabelResponse> executeWithHttpInfo() throws ApiException {
            UpdateJobTier updateJobTier = buildBodyParams();
            return updateLabelWithHttpInfo(id, updateJobTier);
        }

        /**
         * Execute updateLabel request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<JobsInfoUpdateLabelResponse> _callback) throws ApiException {
            UpdateJobTier updateJobTier = buildBodyParams();
            return updateLabelAsync(id, updateJobTier, _callback);
        }
    }

    /**
     * Update a Job Tier
     * Updates the label of a job tier.  Use the #endpoint:3iHo6fSyKNs2dsaSC endpoint to get a list of job tiers, whose &lt;code&gt;id&lt;/code&gt; is used in the path parameters.
     * @param id &lt;code&gt;id&lt;/code&gt; of the job tier you want to view (required)
     * @return UpdateLabelRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public UpdateLabelRequestBuilder updateLabel(List<UpdateJobTierPayload> jobTiers, String id) throws IllegalArgumentException {
        if (jobTiers == null) throw new IllegalArgumentException("\"jobTiers\" is required but got null");
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new UpdateLabelRequestBuilder(jobTiers, id);
    }
}
